load(draw);

/* Specify various ranges
- Basic -
0 <= pa <= 1
0 <= pb <= 1
0 <= max(pa+pb-1, 0) <= x <= min(pa, pb) <= 1
- Derived -
0 <= 1-pa <= 1
0 <= 1-pb <= 1
-1 <= max(-pa, -pb) <= -x <= max(1-pa-pb, 0) <= 0
pa-1 <= max(0, pa-pb) <= pa-x <= max(1-pb, pa) <= pa
pb-1 <= max(pb-pa, 0) <= pb-x <= max(1-pa, pb) <= pb
1-pb-pa <= max(0, 1-pb-pa) <= x-pb-pa+1 <= min(1-pb, 1-pa) <= 2-pb-pa
*/

/* Attempt to solve a few inequalities */
load(to_poly_solve)$
fourier_elim([0 <= pa, pa <= 1, 0 <= pb, pb <= 1], [pa, pb]);

/* Define probability of |A ∧ B| = k using combinations */
cpr(n, a, b, k) := binomial(a, k) * binomial(n - a, b -k) / binomial(n, b);
float(cpr(100, 80, 20, 10));

/* Like cpr but uses probabilities for A, B and |A ∧ B| instead of cardinality */
pcpr(n, pa, pb, x) := binomial(n*pa, n*x) * binomial(n*(1 - pa), n*(pb - x)) / binomial(n, n*pb);
pcpr(70, 0.8, 0.2, 0.1);
/* limit(pcpr(n, 08, 0.2, 0.1), n, inf); */

/* Like cpr but uses factorials instead */
fpcpr(n, pa, pb, x) := (factorial(n*pa) * factorial(n*(1-pa)) * factorial(n*pb) * factorial(n*(1-pb))) / (factorial(n*x) * factorial(n*(pa-x)) * factorial(n*(pb-x)) * factorial(n*(1-pa-pb+x)) * factorial(n));
fpcpr(70, 0.8, 0.2, 0.1);
/* limit(fpcpr(n, 0.8, 0.2, 0.1), n, inf); */

/* Like fpcpr but uses gamma function instead */
gpcpr(n, pa, pb, x) := (gamma(n*pa + 1) * gamma(n*(1-pa) + 1) * gamma(n*pb + 1) * gamma(n*(1-pb) + 1)) / (gamma(n*x + 1) * gamma(n*(pa-x) + 1) * gamma(n*(pb-x) + 1) * gamma(n*(1-pa-pb+x) + 1) * gamma(n + 1));
gpcpr(70, 0.8, 0.2, 0.1);
/* limit(gpcpr(n, 0.8, 0.2, 0.1), n, inf); */

/* Define Stirling approximation */
stirling(n) := sqrt(2*%pi*n)*(n/%e)**n;
float(stirling(70));

/* Like gpcpr but uses Stirling approximation */
stpcpr(n, pa, pb, x) := (stirling(n*pa) * stirling(n*(1-pa)) * stirling(n*pb) * stirling(n*(1-pb))) / (stirling(n*x) * stirling(n*(pa-x)) * stirling(n*(pb-x)) * stirling(n*(1-pa-pb+x)) * stirling(n));
float(stpcpr(70, 0.8, 0.2, 0.1));

/* Simplify Stirling approximation, remove any factors that may cancel out */
/* simp_stirling(n) := sqrt(n)*(n/%e)**n; */
simp_stirling(n) := sqrt(n)*n**n;

/* Like stpcpr but uses simp_stirling */
simp_stpcpr(n, pa, pb, x) := (simp_stirling(n*pa) * simp_stirling(n*(1-pa)) * simp_stirling(n*pb) * simp_stirling(n*(1-pb))) / (simp_stirling(n*x) * simp_stirling(n*(pa-x)) * simp_stirling(n*(pb-x)) * simp_stirling(n*(1-pa-pb+x)) * simp_stirling(n) * sqrt(2*%pi));
float(simp_stpcpr(70, 0.8, 0.2, 0.1));

/* Manually simplified stpcpr */
man_simp_stpcpr(n, pa, pb, x) := (pa**((2*n*pa+1)/2) * pb**((2*n*pb+1)/2) * (pa-x)**((2*n*x-2*n*pa-1)/2) * (pb-x)**((2*n*x-2*n*pb-1)/2)) / (sqrt(2)*sqrt(%pi)*sqrt(n)*(1-pa)**((2*n*pa-2*n-1)/2) * (1-pb)**((2*n*pb-2*n-1)/2) * x**((2*n*x+1)/2) * (x-pb-pa+1)**((2*n*x-2*n*pb-2*n*pa+2*n+1)/2));
/* Like above but distribute 1/2 inside powers */
man_simp_stpcpr(n, pa, pb, x) := (pa**(n*pa+1/2) * pb**(n*pb+1/2) * (pa-x)**(n*x-n*pa-1/2) * (pb-x)**(n*x-n*pb-1/2)) / (sqrt(2)*sqrt(%pi)*sqrt(n)*(1-pa)**(n*pa-n-1/2) * (1-pb)**(n*pb-n-1/2) * x**(n*x+1/2) * (x-pb-pa+1)**(n*x-n*pb-n*pa+n+1/2));
/* Like above but factorize by n inside powers */
man_simp_stpcpr(n, pa, pb, x) := (pa**(n*pa+1/2) * pb**(n*pb+1/2) * (pa-x)**(n*(x-pa)-1/2) * (pb-x)**(n*(x-pb)-1/2)) / (sqrt(2)*sqrt(%pi)*sqrt(n)*(1-pa)**(n*(pa-1)-1/2) * (1-pb)**(n*(pb-1)-1/2) * x**(n*x+1/2) * (x-pb-pa+1)**(n*(x-pb-pa+1)+1/2));
/* Like above but factorize by n inside powers all the way */
man_simp_stpcpr(n, pa, pb, x) := (pa**(n*(pa+1/(2*n))) * pb**(n*(pb+1/(2*n))) * (pa-x)**(n*(x-pa-1/(2*n))) * (pb-x)**(n*(x-pb-1/(2*n)))) / (sqrt(2)*sqrt(%pi)*sqrt(n)*(1-pa)**(n*(pa-1-1/(2*n))) * (1-pb)**(n*(pb-1-1/(2*n))) * x**(n*(x+1/(2*n))) * (x-pb-pa+1)**(n*(x-pb-pa+1+1/(2*n))));
/* Like above but move the factorized n inside powers one level up */
man_simp_stpcpr(n, pa, pb, x) := 1/(sqrt(2)*sqrt(%pi)*sqrt(n)) * ((pa**(pa+1/(2*n)) * pb**(pb+1/(2*n)) * (pa-x)**(x-pa-1/(2*n)) * (pb-x)**(x-pb-1/(2*n))) / ((1-pa)**(pa-1-1/(2*n)) * (1-pb)**(pb-1-1/(2*n)) * x**(x+1/(2*n)) * (x-pb-pa+1)**(x-pb-pa+1+1/(2*n))))**n;
/* Like above but uniformize signs inside the powers */
man_simp_stpcpr(n, pa, pb, x) := 1/(sqrt(2)*sqrt(%pi)*sqrt(n)) * ((pa**(pa+1/(2*n)) * pb**(pb+1/(2*n)) * (1-pa)**(1-pa+1/(2*n)) * (1-pb)**(1-pb+1/(2*n))) / ((pa-x)**(pa-x+1/(2*n)) * (pb-x)**(pb-x+1/(2*n)) * x**(x+1/(2*n)) * (x-pb-pa+1)**(x-pb-pa+1+1/(2*n))))**n;
/* Like above but move the square root factor inside the outer power of n */
man_simp_stpcpr(n, pa, pb, x) := 1/(sqrt(2*%pi)) * ((pa**(pa+1/(2*n)) * pb**(pb+1/(2*n)) * (1-pa)**(1-pa+1/(2*n)) * (1-pb)**(1-pb+1/(2*n))) / (n**(1/(2*n)) * (pa-x)**(pa-x+1/(2*n)) * (pb-x)**(pb-x+1/(2*n)) * x**(x+1/(2*n)) * (x-pb-pa+1)**(x-pb-pa+1+1/(2*n))))**n;
/* Like above but take all 1/(2*n) powers outside of the outer n power */
/* Tip: manually copy/paste to the maxima buffer for best rendering */
man_simp_stpcpr(n, pa, pb, x) := (sqrt(pa*pb*(1-pa)*(1-pb)) / (sqrt(2*%pi*n*(pa-x)*(pb-x)*x*(x-pb-pa+1)))) * ((pa**pa * pb**pb * (1-pa)**(1-pa) * (1-pb)**(1-pb)) / ((pa-x)**(pa-x) * (pb-x)**(pb-x) * x**x * (x-pb-pa+1)**(x-pb-pa+1)))**n;
float(man_simp_stpcpr(70, 0.8, 0.2, 0.1));

/* Derive limit of man_simp_stpcpr */
limit(man_simp_stpcpr(n, pa, pb, x), n, inf);

/* Derive limit of n^(1/(2*n)) (it tends to 1) */
limit(n**(1/(2*n)), n, inf);

/* Attempt to derive the limit of Pr(P_AB <= 0.2) */
/* limit(sum(gpcpr(n, 0.8, 0.2, i/n), i, 0, n*0.2), n, inf); */

/* Draw Pr(P_AB <= x) using gamma form */
draw2d(xrange = [0, 1], explicit(gpcpr(70, 0.8, 0.2, x), x, 0, 0.2));

/* Draw Pr(P_AB <= x) using Stirling form */
draw2d(xrange = [0, 1], explicit(stpcpr(70, 0.8, 0.2, x), x, 0, 0.2));

/* Draw Pr(P_AB <= x) using both gamma and Stirling forms */
draw2d(xrange = [0, 1], explicit(gpcpr(70, 0.8, 0.2, x), x, 0, 0.199),
  color=red, explicit(simp_stpcpr(70, 0.8, 0.2, x), x, 0, 0.199),
  color=green, explicit(man_simp_stpcpr(70, 0.8, 0.2, x), x, 0, 0.199));

/* Draw x^x */
draw2d(xrange = [-1, 1], explicit(x**x, x, -1, 1));

/* Simplfy simp_stpcpr (sort of) */
radcan(simp_stpcpr(n, pa, pb, x));
radcan(man_simp_stpcpr(n, pa, pb, x));
expand(sqrt(2*%pi*n*(pa-x)*(pb-x)*x*(x-pb-pa+1)));
expand((pa-x)*(pb-x)*x*(x-pb-pa+1));
expand((sqrt(pa*pb*(1-pa)*(1-pb)) / (sqrt(2*%pi*n*(pa-x)*(pb-x)*x*(x-pb-pa+1)))))

/* Study sums */
float(sum(gpcpr(70, 0.8, 0.2, i/70), i, 0, 70*0.2));
float(sum(simp_stpcpr(70, 0.8, 0.2, i/70), i, 1, 69*0.2));
float(sum(man_simp_stpcpr(70, 0.8, 0.2, i/70), i, 1, 69*0.2));

/* NEXT: plot various components of man_simp_stpcpr while varying pa,
         pb and x.  The goal is to understand how their powers of n
         should evolve, such as is it greater than 1. */

/* NEXT: Study how to simplify the sum of man_simp_stpcpr, maybe gpcpr
         as well, who knows */

/* NEXT: reformulate man_simp_stpcpr using δt instead of n */

/* NEXT: maybe rename much things, like man_simp_stpcpr by f, pa by p,
         pb by q, etc. */
